==== Overview
Broadleaf API endpoints are backed by Spring Rest Controllers.
The rest controller represents the outward facing API for the microservice. Most commonly,
this component is responsible for little more than de-serializing/serializing JSON input/output
and then passing off to a service component. Out-of-the-box rest controllers may be extended
using standard Java OOP extension. Broadleaf singleton components are annotated to conditionally
load only if a bean of their type does not already exist. And since Broadleaf components are
loaded during the autoconfiguration phase (deferred loader), their ordering is post developer
extensions. Methods may be added or overridden to accomplish new or customized endpoints.
As mentioned in the Business Domain section, Spring Converters may be registered to de-serialize
JSON into more derived business domain types upon endpoint entry. Furthermore, customization of the
JSON output can be achieved with a combination of a `JSONSerializer` implementation and the
`@JsonComponent` annotation. This provides flexibility to hide unwanted fields, modify
field name, etc…​